export const asset = (p) => `${import.meta.env.BASE_URL}${String(p).replace(/^\//, "")}`;

export const DAYS = [
  { key: "mon", short: "Mo", label: "Montag", date: 24 },
  { key: "tue", short: "Di", label: "Dienstag", date: 25 },
  { key: "wed", short: "Mi", label: "Mittwoch", date: 26 },
  { key: "thu", short: "Do", label: "Donnerstag", date: 27 },
  { key: "fri", short: "Fr", label: "Freitag", date: 28 },
  { key: "sat", short: "Sa", label: "Samstag", date: 29 },
  { key: "sun", short: "So", label: "Sonntag", date: 30 },
];

export const initialRecipes = [
  {
    id: "curry",
    title: "Linsencurry mit Spinat",
    time: 25,
    servings: 2,
    tags: ["Schnell", "Meal-Prep"],
    image: asset("img/curry.jpg"),
    source: "chefkoch.de",
    note: "Nächstes Mal weniger Chili, Max fand’s zu scharf.",
    steps: [
      "Zwiebel, Knoblauch und Ingwer fein würfeln.",
      "Öl erhitzen, Zwiebeln anbraten, Gewürze dazu.",
      "Linsen, Tomaten und Kokosmilch einrühren, 15 Min köcheln.",
      "Spinat unterheben, abschmecken und servieren.",
    ],
    ingredients: [
      { id: "i1", name: "rote Linsen", amount: "200 g", category: "Trockenware", have: false },
      { id: "i2", name: "Kokosmilch", amount: "1 Dose (400 ml)", category: "Trockenware", have: true },
      { id: "i3", name: "Zwiebel", amount: "1", category: "Obst & Gemüse", have: true },
      { id: "i4", name: "Knoblauchzehen", amount: "2", category: "Obst & Gemüse", have: false },
      { id: "i5", name: "Ingwer", amount: "1 Stück (ca. 2 cm)", category: "Obst & Gemüse", have: false },
      { id: "i6", name: "stückige Tomaten", amount: "1 Dose (400 g)", category: "Trockenware", have: false },
      { id: "i7", name: "Currypulver", amount: "2 EL", category: "Trockenware", have: false },
      { id: "i8", name: "Kreuzkümmelpulver", amount: "1 TL", category: "Trockenware", have: false },
      { id: "i9", name: "Chiliflocken (optional)", amount: "½ TL", category: "Trockenware", have: false },
      { id: "i10", name: "frischer Spinat", amount: "150 g", category: "Obst & Gemüse", have: false },
      { id: "i11", name: "Salz & Pfeffer", amount: "", category: "Trockenware", have: true },
      { id: "i12", name: "Öl zum Anbraten", amount: "1 EL", category: "Trockenware", have: true },
    ],
  },
  {
    id: "pasta",
    title: "Pasta al Limone",
    time: 25,
    servings: 2,
    tags: ["Schnell"],
    image: asset("img/pasta.jpg"),
    source: "kitchenstories.com",
    note: "Extra Zitrone, nächstes Mal.",
    steps: [
      "Nudeln in Salzwasser al dente kochen, etwas Wasser aufheben.",
      "Butter schmelzen, Zitronenschale und Saft dazugeben.",
      "Nudeln schwenken, Parmesan und Kochwasser zur Sauce binden.",
      "Mit Pfeffer und Petersilie servieren.",
    ],
    ingredients: [
      { id: "p1", name: "Nudeln", amount: "250 g", category: "Trockenware", have: false },
      { id: "p2", name: "Zitrone", amount: "1", category: "Obst & Gemüse", have: false },
      { id: "p3", name: "Parmesan", amount: "60 g", category: "Kühlung", have: false },
      { id: "p4", name: "Butter", amount: "30 g", category: "Kühlung", have: false },
      { id: "p5", name: "Petersilie", amount: "1 Bund", category: "Obst & Gemüse", have: false },
    ],
  },
  {
    id: "pizza",
    title: "Pizza-Abend",
    time: 30,
    servings: 4,
    tags: ["Gäste"],
    image: asset("img/pizza.jpg"),
    source: "eigenes Rezept",
    note: "",
    steps: [
      "Fertigteig ausrollen oder eigenen Teig 10 Min vorbacken.",
      "Tomatensauce, Mozzarella und Belag verteilen.",
      "Bei 220 °C 12–15 Min backen.",
      "Mit Basilikum servieren.",
    ],
    ingredients: [
      { id: "z1", name: "Pizzateig", amount: "2 Stück", category: "Kühlung", have: false },
      { id: "z2", name: "Mozzarella", amount: "250 g", category: "Kühlung", have: false },
      { id: "z3", name: "Passierte Tomaten", amount: "400 g", category: "Trockenware", have: false },
      { id: "z4", name: "Basilikum", amount: "1 Bund", category: "Obst & Gemüse", have: false },
    ],
  },
  {
    id: "feta",
    title: "Pasta mit Spinat und Feta",
    time: 20,
    servings: 2,
    tags: ["Schnell"],
    image: asset("img/pasta-feta.jpg"),
    source: "chefkoch.de",
    note: "",
    steps: [
      "Nudeln kochen.",
      "Spinat in der Pfanne zusammenfallen lassen.",
      "Feta darüberbröseln, mit Pfeffer und Olivenöl abschmecken.",
    ],
    ingredients: [
      { id: "f1", name: "Nudeln", amount: "250 g", category: "Trockenware", have: false },
      { id: "f2", name: "frischer Spinat", amount: "200 g", category: "Obst & Gemüse", have: false },
      { id: "f3", name: "Feta", amount: "200 g", category: "Kühlung", have: false },
      { id: "f4", name: "Olivenöl", amount: "2 EL", category: "Trockenware", have: true },
    ],
  },
];

export const extraShopItems = [
  { id: "e1", name: "Brokkoli", amount: "1", unit: "1 Stück", category: "Obst & Gemüse", checked: false, note: "" },
  { id: "e2", name: "Eier", amount: "6", unit: "6 Stück", category: "Kühlung", checked: true, note: "nur Freiland" },
  { id: "e3", name: "Joghurt Natur", amount: "1 Becher (150g)", unit: "1 Becher (150g)", category: "Kühlung", checked: false, note: "" },
  { id: "e4", name: "Gouda am Stück", amount: "200 g", unit: "200 g", category: "Kühlung", checked: false, note: "" },
  { id: "e5", name: "Basmatireis", amount: "500 g", unit: "500 g", category: "Trockenware", checked: false, note: "" },
  { id: "e6", name: "Spülmittel", amount: "1 Flasche (500ml)", unit: "1 Flasche (500ml)", category: "Haushalt", checked: false, note: "" },
  { id: "e7", name: "Toilettenpapier", amount: "1 Packung (8 Rollen)", unit: "1 Packung (8 Rollen)", category: "Haushalt", checked: true, note: "" },
];

export const initialPlan = {
  mon: null,
  tue: null,
  wed: { recipeId: "curry", meal: "Abend" },
  thu: { recipeId: "pasta", meal: "Abend" },
  fri: { recipeId: "pizza", meal: "Abend", dayNote: "Kinder bei Oma" },
  sat: null,
  sun: null,
};

export const initialNotes = [
  {
    id: "n1",
    type: "reste",
    title: "1/2 Dose Kichererbsen",
    text: "bis Freitag",
    image: asset("img/chickpeas.jpg"),
    action: "Rezept vorschlagen",
  },
  {
    id: "n2",
    type: "plan",
    title: "Donnerstag:",
    text: "Lisa hat Training, Lunchbox packen.",
    pinned: true,
  },
  {
    id: "n3",
    type: "rezepte",
    title: "Pasta al Limone —",
    text: "extra Zitrone, nächstes Mal.",
    recipeId: "pasta",
  },
  {
    id: "n4",
    type: "pin",
    title: "Milch leer",
    text: "",
    handwritten: true,
    pinned: true,
  },
];

export const CATEGORY_META = {
  "Obst & Gemüse": { emoji: "🍎" },
  Kühlung: { emoji: "❄️" },
  Trockenware: { emoji: "📦" },
  Haushalt: { emoji: "🧼" },
};

export const ITEM_EMOJI = {
  Spinat: "🥬",
  "frischer Spinat": "🥬",
  Zwiebel: "🧅",
  Zwiebeln: "🧅",
  Brokkoli: "🥦",
  Eier: "🥚",
  "Joghurt Natur": "🥛",
  "Gouda am Stück": "🧀",
  Parmesan: "🧀",
  Mozzarella: "🧀",
  Feta: "🧀",
  Kokosmilch: "🥥",
  Basmatireis: "🌾",
  Nudeln: "🍝",
  Spülmittel: "🧴",
  Toilettenpapier: "🧻",
  Zitrone: "🍋",
  Knoblauchzehen: "🧄",
  Ingwer: "🫚",
  Butter: "🧈",
  Pizzateig: "🍕",
  Basilikum: "🌿",
  Petersilie: "🌿",
};
